name: universal_form_validation
description: A lightweight, extensible, country-aware form validation package for Flutter & Dart.
version: 0.0.3
homepage: https://github.com/afaq3522/universal_form_validation
repository: https://github.com/afaq3522/universal_form_validation
issue_tracker: https://github.com/afaq3522/universal_form_validation/issues
documentation: https://github.com/afaq3522/universal_form_validation#readme
license: MIT

environment:
  sdk: ^3.10.7
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

topics:
  - form
  - validator
  - flutter
  - validate
  - textformfield

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

